#!/bin/bash
# Retrieve arguments
domain=$1
path=$2
url=$3
sudo yunohost app checkurl $domain$path -a reverseproxy
if [[ ! $? -eq 0 ]]; then
exit 1
fi
# Configure Nginx and reload
sed -i "s@APPPATH@$path@g" ../conf/nginx.conf
sed -i "s@APPURL@$url@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/reverseproxy.conf
sudo service nginx reload
sudo yunohost app ssowatconf

