#!/bin/bash
# Retrieve arguments
domain=$(sudo yunohost app setting reverseproxy domain)
path=$(sudo yunohost app setting reverseproxy path)
# Remove trailing "/" for next commands
path=${path%/}
# Configure Nginx and reload
sed -i "s@APPPATH@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/reverseproxy.conf
sudo service nginx reload
